client_index:
    path:     /
    defaults: { _controller: "FacnoteBundle:Client:index" }
    methods:  GET

client_new_edit:
    path:     /new-edit/{id}
    defaults: { _controller: "FacnoteBundle:Client:form", id: null }
    methods:  [GET, POST]

client_show:
    path:     /{id}/show
    defaults: { _controller: "FacnoteBundle:Client:show" }
    methods:  GET

client_delete:
    path:     /{id}/delete
    defaults: { _controller: "FacnoteBundle:Client:delete" }
    methods:  DELETE
