<?php

namespace FacnoteBundle\Repository;

/**
 * ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientRepository extends \Doctrine\ORM\EntityRepository
{
    public function myFindAll($firstlimit,$maxLimit,$champOrder,$typeOrder){

        $qb = $this->createQueryBuilder('c')
            ->select('c.id','c.nomClient','c.prenomClient','c.adrClient','c.telClient','t.nomType')
            ->join('c.idType', 't')
            ->orderBy('c.' . $champOrder,$typeOrder)
            ->setFirstResult($firstlimit)
            ->setMaxResults($maxLimit);

        return $qb->getQuery()->getResult();
    }

    public function getTotalClient()
    {
        return $this->createQueryBuilder('c')
            ->select('COUNT(c)')
            ->getQuery()
            ->getSingleScalarResult();
    }
}
